language: go
go:
- 1.10.x
- master
script: make test
notifications:
  slack:
    secure: FOI8esC9IeQ0Kb72wUiUPhOmWnkLyIdYMkTZAScXRhNwK97yY+Y/mKbuixzw2hA2hLlWUmxG5/guO06BIVmsIjzedyoYrVYqDKmxRqxafRhqr3QlAlMw8X2YM5ztOSm0GbW/9wmX1y/OvBzKfFl2swObUWAzakkAUYKEV256jcsUaVC++fj9t3mQ94g3OxI+bGs5lqgoSOQpL8To/XqWXdwqpVtWXcETmfu9JFJnuZwasUUifG4TOnj50wL+ghsiVrTz6AfjZINupf36vPMD+2WxNe7gicr6ZzUaK/GsJh65scNekPUbm82uZTH053ZUh+m/NeOz8/lwlzScAdCaH0D3G/vKFYIoOY3MXcDXxVXF/TfeoKpE+1PkUWBiqPGSNlUriRVZ2XIQObSHaIWIVciEEW7hWHcWQWjs2OEG7Pm9y1OiUb+DgOB66KmzMHgqqM9tLlcnGdly5g4ViYRL0nVBesogexI3pivCRYsup7ySlzhQFKwaMg4+FwgNIdsC9Wv4EC+pleB4qca3Kfmb4g1X2K4FiDd5XARLT3JhVtCZ8hlR+TiZhLDFVMCaE3HD6AT/5DaAp/QEfczvVSjsBPcOHj5OLoMWAs2vaQBMi6S4RvYAxdRgQSQiSwX01keqJvmDID5QpFIkDbTGVdUcz+gblTme2yfORNF2O+fHDgs=
